### ISSUE TITLE
JsonMappingException causes NullPointerException

### ISSUE THREAD

**Issue by cyril265** [briandilley/jsonrpc4j#129]
Mapping errors that result in a `JsonMappingException` produce `NullPointerException`. This is caused by the fact that the client tries to get the error stream from the connection if an IOException is thrown. But `JsonMappingException` also extends `IOException`. This means the client will try to get the error stream on `JsonMappingException` and this causes the NPE because the stream is null:

``` java
Caused by: java.lang.NullPointerException: null
    at com.googlecode.jsonrpc4j.NoCloseInputStream.markSupported(NoCloseInputStream.java:85) ~[jsonrpc4j-1.4.3.jar:1.4.3]
    at com.googlecode.jsonrpc4j.ReadContext.assertReadable(ReadContext.java:29) ~[jsonrpc4j-1.4.3.jar:1.4.3]
    at com.googlecode.jsonrpc4j.JsonRpcClient.readResponseNode(JsonRpcClient.java:287) ~[jsonrpc4j-1.4.3.jar:1.4.3]
    at com.googlecode.jsonrpc4j.JsonRpcClient.getValidResponse(JsonRpcClient.java:223) ~[jsonrpc4j-1.4.3.jar:1.4.3]
    at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:173) ~[jsonrpc4j-1.4.3.jar:1.4.3]
    at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:500) ~[jsonrpc4j-1.4.3.jar:1.4.3]
    at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:114) ~[jsonrpc4j-1.4.3.jar:1.4.3]
    at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:92) ~[jsonrpc4j-1.4.3.jar:1.4.3]
```

**Comment by selene-l** [comment]
Yep. Same problem. If the method returns an plain string - it's OK. But if the method returns an object - the library throws _NullPointerException_. For example:

```
{
    "jsonrpc":"2.0",
    "id":"113195884",
    "result":{
        "code":0,
        "message":null,
        "output":{
            "userId":"23f975d1-00af-4ae9-aaca-16863b30e1d0",
            "sessionToken":"cd6405b8-2d4b-4249-8c78-0a647c6cf2a4"
        }
    }
}
```

The stack trace is identical to the listed above. It seems that somewhere missed checking to _null_.

**Comment by adovbnya** [comment]
Almost the same issue with `JsonRpcHttpClient` and **jsonrpc4j** `v1.4.4`: If server SocketTimeout exception occurs - the library catch `java.net.SocketTimeoutException` in this peace of code:
```
try {
	try (InputStream answer = getStream(connection.getInputStream(), useGzip)) {
		return super.readResponse(returnType, answer);
	}
} catch (IOException e) { // <<< java.net.SocketTimeoutException is here
	try (InputStream answer = getStream(connection.getErrorStream(), useGzip)) {
		return super.readResponse(returnType, answer);
	} catch (IOException ef) {
		throw new HttpException(readErrorString(connection), ef);
	}
}
```
and trying to read ErrorStream from connection object. 
But `connection.getErrorStream()` returns `null` and **jsonrpc4j** don't analyze this situation, so result is NPE below:
```
Exception in thread "main" java.lang.NullPointerException
	at com.googlecode.jsonrpc4j.NoCloseInputStream.markSupported(NoCloseInputStream.java:85)
	at com.googlecode.jsonrpc4j.ReadContext.assertReadable(ReadContext.java:29)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponseNode(JsonRpcClient.java:287)
	at com.googlecode.jsonrpc4j.JsonRpcClient.getValidResponse(JsonRpcClient.java:223)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:173)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:500)
	at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:114)
	at com.googlecode.jsonrpc4j.ProxyUtil$3.invoke(ProxyUtil.java:193)
```

**Comment by gaborbernat** [comment]
Not straight forward what would be the expected behavior in this case, but understood thinking of a solution.

**Comment by squallified** [comment]
You could always rethrow the catched IOException if the error stream is null. Seems a bit hacky but it will fix all mentioned cases.

**Comment by adovbnya** [comment]
`JsonRpcRestClient` implementation based on `RestTemplate` do the same thing as @squallified wrote, just rethrow catched IOException exception. So what about my current solution - I just use `JsonRpcRestClient` implementation because my json-rpc transport is HTTP.

**Comment by novy1234** [comment]
I know this is old, but we had same situation. It was caused by not having default constructor for objects sent via JSON

**Comment by dzolo** [comment]
I have got a similar problem. When I send an invalid arguments to a method or do anything else that causes JsonMappingException to be thrown then I will get a NullPointerException on client. The reason is that JsonBasicServer handles all exceptions in invoke method ([line 375](https://github.com/briandilley/jsonrpc4j/blob/master/src/main/java/com/googlecode/jsonrpc4j/JsonRpcBasicServer.java#L375)) to a JSON error but these Jackson exceptions do not have a public constructor. But even if they had one this is invalid behavior.

The fix should be done by rethrowing of IOException that will cause that a proper JsonError.PARSE_ERROR error will be created as response in the [handleRequest](https://github.com/briandilley/jsonrpc4j/blob/master/src/main/java/com/googlecode/jsonrpc4j/JsonRpcBasicServer.java#L245) method.
