### ISSUE TITLE
Pull request 150 broke unit test

### ISSUE THREAD

**Issue by phantomread1** [briandilley/jsonrpc4j#159]
Hi,

https://github.com/briandilley/jsonrpc4j/pull/150

This pull request seems to have broken a unit test:
http405OnInvalidUrl in the HttpCodeTest

`java.lang.AssertionError: 
Expected: (exception with message ("405 HTTP method POST is not supported by this URL" or "404 Not Found") and an instance of org.springframework.web.client.HttpClientErrorException)
     but: exception with message ("405 HTTP method POST is not supported by this URL" or "404 Not Found") message was "HTTP method POST is not supported by this URL"
Stacktrace was: com.googlecode.jsonrpc4j.JsonRpcClientException: HTTP method POST is not supported by this URL
    at com.googlecode.jsonrpc4j.spring.rest.JsonRpcRestClient.invoke(JsonRpcRestClient.java:231)
    at com.googlecode.jsonrpc4j.ProxyUtil$3.invoke(ProxyUtil.java:198)
    at com.sun.proxy.$Proxy32.doSomething(Unknown Source)
    at com.googlecode.jsonrpc4j.integration.HttpCodeTest.http405OnInvalidUrl(HttpCodeTest.java:24)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)`

**Comment by im-scooter** [comment]
@phantomread1, @gaborbernat  
Does the JsonRpcClientException ought to return message with JSON RPC  оr HTTP error code? Is the throwing of HttpException is the better solution to process unsupported  HTTP error codes?
