### ISSUE TITLE
Client proxy only works when called once

### ISSUE THREAD

**Issue by natalieharris** [briandilley/jsonrpc4j#203]
I am using createClientProxy function to create a client proxy. This works fine the first time the proxy is called, but the second this error occurs:

JsonMappingException:
	No content to map due to end-of-input
	 at [Source: com.googlecode.jsonrpc4j.NoCloseInputStream@3e2059ae; line: 1, column: 0]
		at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:256)
		at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3851)
		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
		at com.googlecode.jsonrpc4j.ReadContext.nextValue(ReadContext.java:25)
		at com.googlecode.jsonrpc4j.JsonRpcClient.readResponseNode(JsonRpcClient.java:298)
		at com.googlecode.jsonrpc4j.JsonRpcClient.getValidResponse(JsonRpcClient.java:232)
		at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:182)
		at com.googlecode.jsonrpc4j.JsonRpcClient.invokeAndReadResponse(JsonRpcClient.java:147)
		at com.googlecode.jsonrpc4j.JsonRpcClient.invokeAndReadResponse(JsonRpcClient.java:127)
		at com.googlecode.jsonrpc4j.ProxyUtil$2.invoke(ProxyUtil.java:157)

Has anyone else observed this?

**Comment by mslipper** [comment]
Hi @natalieharris, I can look into this this evening. Would you mind providing me with some code that reproduces the issue?
