### ISSUE TITLE
com.googlecode.jsonrpc4j.JsonRpcClientException:

### ISSUE THREAD

**Issue by niutaifan** [briandilley/jsonrpc4j#211]
This Account Is Locked To Another IP Address.

**Comment by mslipper** [comment]
Hi @niutaifan,

Can you please provide some more context around this issue? I'm not sure what the problem is. Thanks.

**Comment by niutaifan** [comment]
JsonRpcHttpClient client= new JsonRpcHttpClient(new URL(
                    SystemConfig.BITCOIN_URL));
            String cred = Base64.encodeBase64String((SystemConfig.BITCOIN_USER_NAME + ":" + SystemConfig.BITCOIN_USER_PWD).getBytes());
            Map<String, String> headers = new HashMap<String, String>(1);
           headers.put("Authorization", "Basic " + cred);
           client.setHeaders(headers);
 String result =client.invoke("getaccountaddress", new String[]{account}, String.class);
Caused by: com.googlecode.jsonrpc4j.JsonRpcClientException: This Account Is Locked To Another IP Address.
	at com.googlecode.jsonrpc4j.DefaultExceptionResolver.createJsonRpcClientException(DefaultExceptionResolver.java:53)
	at com.googlecode.jsonrpc4j.DefaultExceptionResolver.resolveException(DefaultExceptionResolver.java:28)
	at com.googlecode.jsonrpc4j.JsonRpcClient.handleErrorResponse(JsonRpcClient.java:258)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:184)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:517)
	at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:148)
	at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:118)
	at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:172)

**Comment by mslipper** [comment]
This error is being thrown by the Bitcoin wallet you're connecting to, not JSONRPC4J. See `https://www.reddit.com/r/Bitcoin/comments/26jy1d/locked_out_of_my_blockchain_wallet/` for potential solutions.

**Comment by niutaifan** [comment]
Thanks.
