### ISSUE TITLE
No serializer found for class Args and no properties discovered to create BeanSerializer

### ISSUE THREAD

**Issue by widon1104** [briandilley/jsonrpc4j#215]
The jsonrpc server is written by go:
`package main

import (
    "net"
    "net/rpc"
    "net/rpc/jsonrpc"
)

type Args struct {
	A, B int
}

type Reply struct {
	C int
}

type Arith int

func (t *Arith) Add(args *Args, reply *Reply) error {
	reply.C = args.A + args.B
	return nil
}

func main() {

    rpc.Register(new(Arith))

    addr, _ := net.ResolveTCPAddr("tcp", ":135")
    ln, e := net.ListenTCP("tcp", addr)
    if e != nil {
        panic(e)
    }
    for {
        conn, e := ln.Accept()
        if e != nil {
            continue
        }
        go jsonrpc.ServeConn(conn)
    }
}`

The client is written by java use jsonrpc4j:
`import com.googlecode.jsonrpc4j.JsonRpcClient;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.*;

class Reply {
	int c;
}

class Args {
	int a;
	int b;
}

public class SocketClient {

    public static void main(String[] args) {
        try {
            Socket socket = new Socket("127.0.0.1", 135);
            JsonRpcClient client = new JsonRpcClient();

            InputStream ips = socket.getInputStream();
            OutputStream ops = socket.getOutputStream();

	     Args addargs = new Args();
	     addargs.a = 10;
	     addargs.b = 20;
             Reply reply = client.invokeAndReadResponse("Arith.Add", addargs, Reply.class, ops, ips);  

            System.out.println("reply: " + reply.c);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        }

    }
}
`
After I run my client code:
widon@widon-H61M-S2V-B3:~/test/jsonrpc/SocketClient$ java -cp jsonrpc4j-0.27.jar:jackson-databind-2.5.0.jar:jackson-core-2.7.4.jar:jackson-annotations-2.7.3.jar:. SocketClient
java.lang.IllegalArgumentException: No serializer found for class Args and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2370)
	at com.googlecode.jsonrpc4j.JsonRpcClient.internalWriteRequest(JsonRpcClient.java:402)
	at com.googlecode.jsonrpc4j.JsonRpcClient.writeRequest(JsonRpcClient.java:325)
	at com.googlecode.jsonrpc4j.JsonRpcClient.invoke(JsonRpcClient.java:191)
	at com.googlecode.jsonrpc4j.JsonRpcClient.invokeAndReadResponse(JsonRpcClient.java:127)
	at com.googlecode.jsonrpc4j.JsonRpcClient.invokeAndReadResponse(JsonRpcClient.java:79)
	at com.googlecode.jsonrpc4j.JsonRpcClient.invokeAndReadResponse(JsonRpcClient.java:102)
	at SocketClient.main(SocketClient.java:33)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class Args and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:59)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2238)
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2365)
	... 7 more

How can I use jsonrpc4j to finish my job?

**Comment by wuwen5** [comment]
The ```Args``` and ```Reply ```  requirement has getter/setter method.

```java 
class Args {
    int a;
    int b;
    public int getA() {
        return a;
    }
    public void setA(int a) {
        this.a = a;
    }
    public int getB() {
        return b;
    }
    public void setB(int b) {
        this.b = b;
    }
}
```
or
```java 
class Args {
    public int a;
    public int b;
}
```
