### ISSUE TITLE
"No content to map due to end-of-input" exception while reading message from InputStream...

### ISSUE THREAD

**Issue by sudheerd** [briandilley/jsonrpc4j#27]
Hi,

While reading JSON-RPC message by using JsonRpcClient::readResponse() API, sometimes it throws the following exception:

---------------------------------------------
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
at [Source: com.googlecode.jsonrpc4j.NoCloseInputStream@52853dcb; line: 1, column: 1]
          at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
          at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:2836)
          at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapp...
----------------------------------------------

Why this exception occurs? 

How to handle this exception?

Do I need to reset the connection when this exception occurs?

Please let me know.

Thanks,
Sudheer

**Comment by gaborbernat** [comment]
closing this until you can show a code to reproduce this :)
