### ISSUE TITLE
gzip compression in client?

### ISSUE THREAD

**Issue by Koizumi85** [briandilley/jsonrpc4j#94]
Hello,

is it possible request with "Accept-Encoding: gzip, deflate", such that the JsonRpcHttpClient can consume them? 
I have tried to simply set headers.put("Accept-Encoding", "gzip, deflate"); and put them into the client. But then i get the following exception, because the Jackson mapper can not handle the gzipped compressed string.

````
 com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: com.googlecode.jsonrpc4j.NoCloseInputStream@1ab92ec8; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:459)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2625)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:645)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1802)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:241)
	at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:160)
	... 95 common frames omitted
````

Is there a possibility to enable a decompression in JsonRpcHttpClient, so that this works? Would be very nice, because the responses we get here are around 9 MB in size.

Best Regards

**Comment by Koizumi85** [comment]
No comment on this?
If someone could give me a hint where/how to implement it, i would try it myself.
