### ISSUE TITLE
JsonMappingException: No content to map due to end-of-input

### ISSUE THREAD

**Issue by jbri7357** [briandilley/jsonrpc4j#97]
I have set up a simple Spring Boot project based on a tutorial I've found at:
https://dzone.com/articles/is-java-remote-procedure-call-dead-in-the-rest-age

I'm using Spring Boot 1.3.0 and Jackson 2.6.3.

Using the code from the article above, I receive the following error when I try to access the service:

com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: com.googlecode.jsonrpc4j.NoCloseInputStream@7e517708; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2796) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.googlecode.jsonrpc4j.ReadContext.nextValue(ReadContext.java:59) ~[jsonrpc4j-1.2.0.jar:na]
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handle(JsonRpcBasicServer.java:172) ~[jsonrpc4j-1.2.0.jar:na]
	at com.googlecode.jsonrpc4j.JsonRpcServer.handle(JsonRpcServer.java:178) ~[jsonrpc4j-1.2.0.jar:na]
	at com.googlecode.jsonrpc4j.spring.JsonServiceExporter.handleRequest(JsonServiceExporter.java:64) ~[jsonrpc4j-1.2.0.jar:na]

**Comment by SubOptimal** [comment]
The problem (most probably) is that you don't specify the right content type `Content-Type: application/json` when you POST the request. If you don't explicitly specify it `Content-Type: application/x-www-form-urlencoded` will be choosen which will lead in your exception.

To specify the content type use `curl -H "Content-Type: application/json" ...`

Find a working example related to the post at https://github.com/SubOptimal/spring-boot-jsonrpc4j

**Comment by jbri7357** [comment]
Yes. This appears to be exactly what the problem was. Thanks so much.
